package com.fsd.exp6.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

/**
 * PART A & B — User Entity
 *
 * Demonstrates:
 *  - Basic JPA entity with @Entity, @Table, @Id, @GeneratedValue
 *  - Many-to-Many relationship with Role via a join table "user_roles"
 *
 * SQL generated by Hibernate (shown in console):
 *  CREATE TABLE users (id BIGINT, username VARCHAR, email VARCHAR, password VARCHAR)
 *  CREATE TABLE user_roles (user_id BIGINT, role_id BIGINT)
 */
@Entity
@Table(name = "users",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = "username"),
                @UniqueConstraint(columnNames = "email")
        })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = "roles")  // avoid circular toString
public class User {

    /** Primary key — auto-incremented by the DB */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Column(nullable = false, length = 50)
    private String username;

    @NotBlank
    @Column(nullable = false, length = 100)
    private String email;

    @Column(nullable = false)
    private String password;

    /**
     * MANY-TO-MANY: A user can have multiple roles; a role can belong to multiple users.
     *
     * Hibernate generates a join table:
     *   CREATE TABLE user_roles (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL)
     *
     * FetchType.LAZY — roles are NOT loaded unless explicitly accessed (prevents N+1).
     * CascadeType.MERGE — persisting/merging a user will cascade to roles.
     */
    @ManyToMany(fetch = FetchType.LAZY,
                cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
            name = "user_roles",
            joinColumns        = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    @Builder.Default
    private Set<Role> roles = new HashSet<>();

    // ----- Helper Methods -----

    public void addRole(Role role) {
        this.roles.add(role);
        role.getUsers().add(this);
    }

    public void removeRole(Role role) {
        this.roles.remove(role);
        role.getUsers().remove(this);
    }
}
